import {Contract,Interface,JsonRpcProvider,keccak256,formatEther,toBeHex,ZeroAddress} from '../vendor/ethers-6.15.0.js';
import {findWalletProvider,rememberWalletProvider} from '../../assets/wallet-session.js?v=wallet-session-95';
import {switchWalletChain} from '../../assets/wallet-chain-switch.js?v=chain-switch-132';
import {OWNER,buildPlan} from './plan.js';
const $=s=>document.querySelector(s),same=(a,b)=>a?.toLowerCase()===b?.toLowerCase(),status=s=>$('#status').textContent=s;
const get=async file=>{const r=await fetch(file);if(!r.ok)throw Error('Launch package unavailable');return r.json();};
const [configs,artifacts,rehearsals]=await Promise.all(['config.json','artifacts.json','rehearsals.json'].map(get));
let wallet,plan,run={},busy=false,connected=false;
const selected=new URLSearchParams(location.search).get('chain');if(configs[selected])$('#chain').value=selected;
const chain=()=>$('#chain').value,key=()=>`more-multichain-launch-1:${chain()}:${OWNER.toLowerCase()}`;
const provider=()=>new JsonRpcProvider(configs[chain()].rpc,configs[chain()].id,{staticNetwork:true});
const iface=n=>new Interface(artifacts[n].abi),persist=()=>localStorage.setItem(key(),JSON.stringify({plan,run}));
const log=s=>$('#log').textContent+='\n'+s;
function render(){const c=configs[chain()];$('#cap').textContent=chain()==='eth'?'1 ETH per swap':'10 AVAX per swap';$('#chain').disabled=busy||Boolean(run.hashes?.length&&!run.verified);$('#connect').disabled=busy;$('#prepare').disabled=busy||!connected||Boolean(run.hashes?.length);$('#deploy').disabled=busy||!connected||!plan||Boolean(run.verified);$('#verify').disabled=busy||!run.hashes?.[1];$('#download').disabled=!plan;$('#deploy').textContent=run.hashes?.[0]?'Deploy full protocol · step 2':'Deploy helper · step 1';if(run.hashes?.[1])$('#deploy').textContent='Check deployment confirmation';if(plan){$('#anchor').textContent=new Date(plan.anchor*1000).toLocaleString();$('#deadline').textContent=new Date((plan.anchor+8*86400)*1000).toLocaleString();}for(let i=0;i<2;i++)if(run.hashes?.[i])$('#step'+(i+1)).textContent=run.hashes[i];}
function restore(){const saved=JSON.parse(localStorage.getItem(key())||'null');plan=saved?.plan;run=saved?.run||{};connected=false;$('#cost').textContent='Check and prepare to refresh the estimate';$('#anchor').textContent='Not prepared';$('#deadline').textContent='—';$('#step1').textContent='Deploy committed helper';$('#step2').textContent='Deploy and lock the complete protocol';$('#log').textContent='No transactions submitted.';status(plan?'Saved launch found. Connect your deployment wallet to resume.':'Connect your deployment wallet to begin.');render();}
async function action(fn){if(busy)return;busy=true;render();try{await fn();}catch(e){status(e.shortMessage||e.message);log(e.shortMessage||e.message);}finally{busy=false;render();}}
async function walletCheck(){if(!wallet)throw Error('Connect the deployment wallet first.');const [accounts,id]=await Promise.all([wallet.request({method:'eth_accounts'}),wallet.request({method:'eth_chainId'})]);if(!same(accounts[0],OWNER))throw Error('Select the confirmed deployment wallet.');if(Number(BigInt(id))!==configs[chain()].id)throw Error('Wallet network changed. Reconnect on the selected network.');}
function planCheck(){if(!plan||plan.owner!==OWNER||plan.chain!==chain()||plan.chainId!==configs[chain()].id)throw Error('Saved plan identity mismatch');const rebuilt=buildPlan(chain(),configs[chain()],artifacts,plan.nonce,plan.anchor+1);if(rebuilt.planHash!==plan.planHash||JSON.stringify(rebuilt.transactions)!==JSON.stringify(plan.transactions))throw Error('Saved plan no longer matches this launch package');}
async function poolsCheck(r){const c=configs[chain()];for(const i of [0,1,2]){if(chain()==='eth'&&i===1){const state=new Contract(c.stateView,['function getSlot0(bytes32) view returns(uint160,int24,uint24,uint24)','function getLiquidity(bytes32) view returns(uint128)'],r);if((await state.getSlot0(c.pools[i]))[0]===0n||await state.getLiquidity(c.pools[i])===0n)throw Error('MORE pool is unavailable');}else{const pool=new Contract(c.pools[i],['function token0() view returns(address)','function token1() view returns(address)','function liquidity() view returns(uint128)'],r),[t0,t1,l]=await Promise.all([pool.token0(),pool.token1(),pool.liquidity()]);if(l===0n||!((same(t0,c.native)&&same(t1,c.tokens[i]))||(same(t1,c.native)&&same(t0,c.tokens[i]))))throw Error('Pool token or liquidity check failed');}}log('All three selected token pools have liquidity and matching tokens.');}
async function helperCheck(r){const hash=run.hashes?.[0];if(!hash)throw Error('No helper transaction saved');const [receipt,tx]=await Promise.all([r.getTransactionReceipt(hash),r.getTransaction(hash)]);if(!receipt)throw Error('Helper is still confirming. Check again after it confirms.');if(receipt.status!==1||!same(receipt.contractAddress,plan.helper)||!same(tx.from,OWNER)||tx.nonce!==plan.nonce||tx.data!==plan.transactions[0].data)throw Error('Helper receipt does not match this plan');const helper=new Contract(plan.helper,artifacts.MoreForgeDeployerV2.abi,r);if(!same(await helper.owner(),OWNER)||await helper.planHash()!==plan.planHash)throw Error('Helper commitment mismatch');return receipt;}
async function verify(){planCheck();const r=provider();await helperCheck(r);const [receipt,tx]=await Promise.all([r.getTransactionReceipt(run.hashes?.[1]),r.getTransaction(run.hashes?.[1])]);if(!receipt)throw Error('Full deployment is still confirming.');if(receipt.status!==1||!same(tx.from,OWNER)||!same(tx.to,plan.helper)||tx.nonce!==plan.nonce+1||tx.data!==plan.transactions[1].data)throw Error('Full deployment receipt mismatch');const C=plan.contracts;for(const address of Object.values(C))if(await r.getCode(address)==='0x')throw Error('A deployed contract is missing');const contract=(label,name)=>new Contract(C[label],artifacts[name].abi,r),pos=contract('position','MoreForgePositionV2'),btc=contract('bitcoinVault','MoreBitcoinRewardVaultV2'),drip=contract('dripController','MoreDailyBurnController');if(await pos.owner()!==ZeroAddress||await btc.owner()!==ZeroAddress||await pos.entriesPaused()||await pos.feeBps()!==10000n||await pos.feeBoundsEnabled()||!same(await pos.more(),configs[chain()].tokens[1])||!same(await pos.feeReceiver(),C.feeRouter)||!same(await btc.rewardToken(),configs[chain()].tokens[2])||!same(await drip.rateManager(),OWNER))throw Error('Permanent launch setting mismatch');for(const label of ['fuelBurner','moreBurner']){const b=contract(label,'ForkBurnEngine');if(!same(await b.owner(),C.dripController)||await b.maxSwapEth()!==BigInt(configs[chain()].cap)||await b.maxSlippageBps()!==1000n||!(await drip.isBurnEngine(C[label])))throw Error('Burn ownership or limit mismatch');}run.verified=true;run.deploymentBlock=receipt.blockNumber;run.receipts=[await r.getTransactionReceipt(run.hashes[0]),receipt];persist();status('Deployment confirmed and checked. Download the report and send it in the chat so the public site can be connected and source verification can begin.');log('All deployed contracts and locked controls verified.');}
$('#connect').onclick=()=>action(async()=>{const selected=await findWalletProvider(false);if(!selected)throw Error('Open in Rabby or another wallet browser.');wallet=selected.provider;rememberWalletProvider(wallet);await wallet.request({method:'eth_requestAccounts'});await switchWalletChain(wallet,{...configs[chain()],name:chain()==='eth'?'Ethereum Mainnet':'Avalanche C-Chain',explorer:chain()==='eth'?'https://etherscan.io':'https://snowtrace.io'});await walletCheck();connected=true;status('Deployment wallet connected.');});
$('#prepare').onclick=()=>action(async()=>{await walletCheck();const r=provider();await poolsCheck(r);const [block,nonce,gasPrice,balance]=await Promise.all([r.getBlock('latest'),r.getTransactionCount(OWNER,'pending'),r.send('eth_gasPrice',[]),r.getBalance(OWNER)]);plan=buildPlan(chain(),configs[chain()],artifacts,nonce,block.timestamp);run={hashes:[]};const gas1=await r.estimateGas(plan.transactions[0]),gas2=BigInt(rehearsals[chain()].gas[1]);const estimate=(gas1+gas2)*BigInt(gasPrice);$('#cost').textContent=`≈ ${formatEther(estimate)} ${configs[chain()].unit} at the current gas price. Your wallet gives the final estimate.`;if(balance<estimate*120n/100n)throw Error('Wallet needs more native gas funds before deployment.');persist();log('Package prepared. Full protocol rehearsal passed real swaps, stake, burns, all four claims, and withdrawal.');status('Ready for your wallet approval of step 1.');});
$('#deploy').onclick=()=>action(async()=>{await walletCheck();planCheck();const r=provider();if(run.hashes?.[1]){await verify();return;}if(run.hashes?.[0])await helperCheck(r);const step=run.hashes?.[0]?1:0,nonce=await r.getTransactionCount(OWNER,'pending');if(nonce!==plan.nonce+step)throw Error('Wallet nonce changed. Do not deploy this saved plan. Return to the chat before continuing.');await poolsCheck(r);const tx=plan.transactions[step],estimated=await r.estimateGas(tx),gas=estimated*110n/100n;if(chain()==='eth'&&gas>16777216n)throw Error('Ethereum transaction exceeds the tested gas limit. Return to the chat.');await walletCheck();run.hashes[step]=await wallet.request({method:'eth_sendTransaction',params:[{...tx,chainId:toBeHex(configs[chain()].id),gas:toBeHex(gas)}]});persist();log(`Step ${step+1} submitted: ${run.hashes[step]}`);status('Transaction submitted. Wait for wallet confirmation, then use the next step.');});
$('#verify').onclick=()=>action(verify);$('#chain').onchange=()=>{history.replaceState(null,'',location.pathname+'?chain='+chain());restore();};
$('#download').onclick=()=>{const blob=new Blob([JSON.stringify({plan,run},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`more-forge-${chain()}-deployment.json`;a.click();URL.revokeObjectURL(url);};
restore();
