const $=id=>document.getElementById(id);
let paired=false,demo=false;
const fmt=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:4}).format(n);
export function feeBreakdown(receipts,stake){if(!Number.isFinite(receipts)||receipts<0)throw new Error('Invalid receipt amount');return {gross:receipts,fee:stake?receipts*.1:0,stakers:stake?receipts*.07:0,dev:stake?receipts*.03:0,net:stake?receipts*.9:receipts};}
function quote(){const eth=Number($('eth').value),fuel=Number($('fuel').value);return feeBreakdown(Math.max(0,Number.isFinite(eth)?eth:0)*100+(paired?Math.max(0,Number.isFinite(fuel)?fuel:0)/1e6:0),document.querySelector('[name=destination]:checked').value==='stake');}
function update(){const q=quote(),stake=document.querySelector('[name=destination]:checked').value==='stake';$('net').textContent=fmt(q.net);$('gross').textContent=`${fmt(q.gross)} LP`;$('entry').textContent=`${fmt(q.fee)} LP · ${stake?10:0}%`;$('stakers').textContent=`${fmt(q.stakers)} LP`;$('dev').textContent=`${fmt(q.dev)} LP`;$('receive').textContent=`${fmt(q.net)} ${stake?'staked':'wallet'} receipts`;$('destination-title').textContent=stake?'Your Hourglass stake':'Receipts in your wallet';}
function show(title,body){$('modal-title').textContent=title;$('modal-body').textContent=body;$('modal').showModal();}
function mode(pair){paired=pair;$('fuel-label').hidden=!pair;$('eth-tab').setAttribute('aria-pressed',!pair);$('pair-tab').setAttribute('aria-pressed',pair);$('deposit-note').textContent=pair?'Your FUEL and ETH create liquidity together. Unused FUEL/WETH returns to your wallet.':'The zap wraps ETH, buys FUEL with part of it, and adds both assets to liquidity.';update();}
$('eth-tab').onclick=()=>mode(false);$('pair-tab').onclick=()=>mode(true);
document.querySelectorAll('input').forEach(el=>el.addEventListener('input',update));
document.querySelectorAll('[data-tab]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.tab').forEach(el=>el.hidden=el.id!==btn.dataset.tab);document.querySelectorAll('[data-tab]').forEach(el=>el.classList.toggle('selected',el===btn));});
$('review').onclick=()=>{const eth=Number($('eth').value),fuel=Number($('fuel').value),slip=Number($('slippage').value),deadline=Number($('deadline').value);if(!(eth>0)||paired&&!(fuel>0)||!(slip>=.1&&slip<=5)||!(deadline>=1&&deadline<=60)){$('validation').textContent='Enter positive deposit amounts, slippage from 0.1–5%, and a deadline from 1–60 minutes.';return;}$('validation').textContent='Preview only. No transaction will be sent.';const q=quote();show('Your sample deposit',`${fmt(eth)} ETH${paired?' + '+fmt(fuel)+' FUEL':''} → ${fmt(q.gross)} sample receipts. Entry fee: ${fmt(q.fee)} LP (${fmt(q.stakers)} to stakers, ${fmt(q.dev)} to development). You receive ${fmt(q.net)} receipts. This is an illustrative calculation, not a live quote.`);};
$('wallet').onclick=()=>{demo=!demo;$('wallet').textContent=demo?'Demo wallet active':'Try demo wallet';$('wallet-state').textContent=demo?'Sample wallet · balances below are illustrative.':'Try the demo wallet to explore a sample position.';$('stake-balance').textContent=demo?'100 LP receipts':'—';$('reward-balance').textContent=demo?'1 LP receipt':'—';$('wallet-balance').textContent=demo?'0 LP receipts':'—';$('claim').disabled=!demo;exitUpdate();};
function exitUpdate(){const value=Number($('withdraw').value),valid=Number.isFinite(value)&&value>0&&value<=100;const q=feeBreakdown(valid?value:0,true);$('exit-fee').textContent=valid?`${fmt(q.fee)} LP`:'Enter 0–100 LP';$('exit-split').textContent=`${fmt(q.stakers)} LP / ${fmt(q.dev)} LP`;$('exit-net').textContent=`${fmt(q.net)} LP`;$('exit').disabled=!demo||!valid;return q;}
$('withdraw').addEventListener('input',exitUpdate);$('exit').onclick=()=>{const q=exitUpdate();show('Your sample withdrawal',`Unstake ${fmt(q.gross)} receipts. The 10% exit fee is ${fmt(q.fee)} receipts; ${fmt(q.net)} LP receipts return to your wallet. Underlying token redemption is not included in this preview.`);};
$('claim').onclick=()=>show('Sample reward claim','This example would move 1 claimable LP receipt to your wallet. No transaction is submitted and sample balances stay unchanged.');$('compound-action').onclick=()=>show('Sample compound','2 new LP units: 1 backs staker rewards, and 1 belongs to the protocol. Total liquidity would rise from 302 to 304. This does not change the sample balances.');
document.querySelectorAll('.close').forEach(btn=>btn.onclick=()=>$('modal').close());update();exitUpdate();
