'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const f=(n,d=4)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(Number(n.toPrecision(12)));
const config={rh:{name:'Robinhood',unit:'ETH',usd:2700,btc:'cbBTC'},pls:{name:'PulseChain',unit:'PLS',usd:0.00001,btc:'wBTC'},eth:{name:'Ethereum',unit:'ETH',usd:2700,btc:'wBTC'},avax:{name:'Avalanche',unit:'AVAX',usd:25,btc:'BTC token · pending'}};
const poolWeights=[{days:8,bps:2688,balanceUsd:1500,left:3},{days:28,bps:2268,balanceUsd:2500,left:15},{days:88,bps:1764,balanceUsd:4500,left:35},{days:288,bps:1680,balanceUsd:6000,left:21,bitcoin:true}];
const bitcoinUsd=83000;
const poolUnit=p=>p.bitcoin?selected().btc:selected().unit;
const poolPrice=p=>p.bitcoin?bitcoinUsd:selected().usd;
const moreUsd=.001, sampleBalance='12000000', existingPower=5000000;
let rates={MORE:1,FUEL:1,PAMP:1};
const selected=()=>config[$('#chain').value];
function values(){const raw=Number($('#amount').value);const days=Number($('#term').value);const valid=Number.isFinite(raw)&&raw>0&&raw<=Number(sampleBalance)&&Number.isInteger(days)&&days>=8&&days<=1000;const amount=valid?raw:0, term=Number.isFinite(days)?Math.max(8,Math.min(1000,Math.trunc(days))):8;const bigger=1+Math.min(amount/1000,1),longer=1+1.5*(term-8)/992,power=amount*bigger*longer,feeUsd=amount*moreUsd;return{amount,term,bigger,longer,power,feeUsd,fee:feeUsd/selected().usd,share:power/(existingPower+power),valid};}
function update(){const v=values(),c=selected();$('#burn-value').textContent=`${f(v.amount)} MORE ≈ $${f(v.feeUsd,2)}`;$('#native-fee').textContent=`≈ ${f(v.fee,8)} ${c.unit} · $${f(v.feeUsd,2)}`;$('#total-cost').textContent=`≈ $${f(v.feeUsd*2,2)} USD`;$('#multiplier').textContent=`${f(v.bigger*v.longer,3)}×`;$('#power').textContent=`${f(v.power)} power`;$('#power-ring').style.setProperty('--power-angle',`${v.valid?Math.min(1,v.bigger*v.longer/5)*360:0}deg`);$('#share').textContent=`${f(v.share*100,4)}%`;$('#amount-bonus').textContent=`${f(v.bigger,4)}×`;$('#term-bonus').textContent=`${f(v.longer,4)}×`;$$('[data-term]').forEach(b=>b.classList.toggle('active',Number(b.dataset.term)===v.term));$('#payouts').innerHTML=poolWeights.map(p=>{const eligible=v.term>=p.left,payout=eligible?(p.balanceUsd+v.feeUsd*p.bps/10000)*.9975*v.share:0;return `<div><b>${p.days} Day<small>Closes in ${p.left}d · sample</small></b><div><strong>${eligible?'≈ '+f(payout/poolPrice(p),8)+' '+poolUnit(p):'Term too short'}</strong><small>${eligible?'≈ $'+f(payout,2)+' USD':'Closes in '+p.left+' sample days'}</small></div></div>`}).join('');$('#build-form .primary-button').disabled=!v.valid;drawPools(v);drawTermEstimate(v);$('#hero-native').textContent='$'+c.unit;$('#hero-bitcoin').textContent=c.btc.includes('pending')?'BTC · pending':'$'+c.btc;$('.native-symbol').textContent=c.unit==='ETH'?'◇':c.unit==='PLS'?'⬡':'△';drawBurns();}
function burnIcon(symbol){return `assets/${symbol.toLowerCase()}-token.jpg`;}
function drawBurns(){const c=selected();$('#burns').innerHTML=['MORE','FUEL','PAMP'].map(symbol=>{const balance=500/c.usd,gross=balance*rates[symbol]/100/144;return `<article class="card burn-card"><div class="burn-heading"><img class="burn-token-icon ${symbol==='FUEL'?'fuel-burn-icon':''}" src="${burnIcon(symbol)}" alt="${symbol} logo" width="56" height="56"><h3>$${symbol}</h3></div><div class="burn-settings"><span class="burn-share"><strong>5%</strong> of protocol fees · fixed</span><span class="burn-drip"><label for="drip-${symbol}">Daily drip · preview operator setting</label><select id="drip-${symbol}" data-drip="${symbol}">${Array.from({length:10},(_,i)=>`<option value="${i+1}" ${rates[symbol]===i+1?'selected':''}>${i+1}% per day</option>`).join('')}</select></span></div><div class="burn-balance"><span>Sample burn-pool balance</span><strong>${f(balance,6)}</strong><small>${c.unit}</small></div><div class="burn-row"><span>Next 10-minute interval</span><strong>${f(gross,8)} ${c.unit}</strong></div><div class="burn-row"><span>Caller reward · 1.5%</span><strong>${f(gross*.015,10)} ${c.unit}</strong></div><div class="burn-row"><span>Swap and burn budget</span><strong>${f(gross*.985,10)} ${c.unit}</strong></div><button class="primary-button" data-burn="${symbol}">Preview ${symbol} burn ↗</button></article>`}).join('');$$('[data-drip]').forEach(e=>e.onchange=()=>{rates[e.dataset.drip]=Number(e.value);drawBurns()});$$('[data-burn]').forEach(e=>e.onclick=()=>show(`Buy & burn ${e.dataset.burn}`,`5% of every protocol fee funds this pool. The operator may set a 1–10% daily drip. Eligible callers receive the existing 1.5% execution incentive; the remainder swaps into ${e.dataset.burn} and goes to the burn address.\n\nSample only. No swap, burn or wallet request occurs.`));}
function show(title,body){$('#review-title').textContent=title;$('#review-body').textContent=body;$('#review').showModal();}
$('#review-close').onclick=$('.dialog-close').onclick=()=>$('#review').close();
$('#build-form').onsubmit=e=>{e.preventDefault();const v=values();if(!v.valid)return;show('Review your MORE Forge position',`${f(v.amount)} MORE permanently burned (sample value $${f(v.feeUsd,2)}).\nSeparate protocol fee: ${f(v.fee,8)} ${selected().unit}, equal to $${f(v.feeUsd,2)}.\nCombined entry value: $${f(v.feeUsd*2,2)} before gas.\nReward term: ${v.term} days. Proposed power: ${f(v.power)}.\n\nThere is no principal refund. Fee routing is fixed at 84% payout pools, 1% development and 5% each for MORE/FUEL/PAMP buy & burn. The bonus formula is proposed. This demo never opens your wallet.`)};
$('#amount').oninput=()=>{let s=$('#amount').value.replace(/[^0-9.]/g,'');let[a,...b]=s.split('.');$('#amount').value=a+(b.length?'.'+b.join('').slice(0,18):'');update()};$('#term').oninput=update;$('#chain').onchange=()=>{update();window.dispatchEvent(new Event('more-chain-change'));};$('#max-amount').onclick=()=>{$('#amount').value=sampleBalance;update()};$('#max-term').onclick=()=>{$('#term').value='1000';update()};$$('[data-term]').forEach(b=>b.onclick=()=>{$('#term').value=b.dataset.term;update()});
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(t=>t.setAttribute('aria-selected',String(t===b)));$$('[role=tabpanel]').forEach(p=>p.hidden=p.id!==`panel-${b.dataset.tab}`);$('.hero').hidden=b.dataset.tab!=='build';$('.burn-summary').hidden=b.dataset.tab!=='build';history.replaceState(null,'','#'+b.dataset.tab);});
$('#bonus-examples').innerHTML=[100,500,1000,2000].map(n=>{const m=1+Math.min(n/1000,1);return `<tr><td>${f(n)} MORE</td><td>${f(m,4)}×</td><td>${f(n*m)} power</td><td>${f(n*m*2.5)} power</td></tr>`}).join('');
function drawTermEstimate(v){
 const c=selected();let nativeUsd=0,btcUsd=0;
 $('#term-estimate-title').textContent=`Estimated rewards over your ${f(v.term,0)}-day term`;
 $('#term-payouts').innerHTML=poolWeights.map(p=>{
  const result=MoreForgeEstimates.termReward({term:v.term,firstDeadline:p.left,cycleDays:p.days,fundingUsd:p.balanceUsd,feeUsd:v.feeUsd,allocationBps:p.bps,share:v.share,valid:v.valid});
  if(p.bitcoin)btcUsd+=result.usd;else nativeUsd+=result.usd;
  return `<div><b>${p.days} Day<small>${result.count} eligible ${result.count===1?'deadline':'deadlines'}</small></b><div><strong>≈ ${f(result.usd/poolPrice(p),8)} ${poolUnit(p)}</strong><small>≈ $${f(result.usd,2)} USD</small></div></div>`;
 }).join('');
 $('#term-native-total').textContent=`≈ ${f(nativeUsd/c.usd,8)} ${c.unit}`;
 $('#term-bitcoin-total').textContent=`+ ${f(btcUsd/bitcoinUsd,8)} ${c.btc}`;
 $('#term-usd-total').textContent=`≈ $${f(nativeUsd+btcUsd,2)} USD combined`;
 $('#detail-burned').textContent=`${f(v.amount)} MORE`;
 $('#detail-term').textContent=`${f(v.term,0)} days`;
 $('#sample-calculation-prices').textContent=`Calculator sample prices: MORE $${moreUsd}; ${c.unit} $${f(c.usd,8)}; ${c.btc} $${f(bitcoinUsd,2)}. These sample prices are separate from the market references above.`;
}
update();
if(location.hash==='#pools')$('[data-tab="pools"]').click();

function drawPools(v){
 const c=selected(),nativeUsd=poolWeights.filter(p=>!p.bitcoin).reduce((n,p)=>n+p.balanceUsd,0);
 $('#pool-overview').innerHTML=`<div><span>IN CURRENT FORGE CYCLES</span><strong>${f(nativeUsd/c.usd,6)} ${c.unit}</strong><b>≈ $${f(nativeUsd,2)} USD · sample</b><small>Across the 8-, 28- and 88-day pools</small></div><div><span>288-DAY BITCOIN CYCLE</span><strong>${f(6000/bitcoinUsd,8)} ${c.btc}</strong><b>≈ $6,000 USD · sample</b><small>Open to every eligible MORE position</small></div><div><span>YOUR PREVIEW POSITION</span><strong>${f(v.power)} power</strong><b>${f(v.share*100,4)}% estimated share after entry</b><small>${f(v.term,0)}-day term · simulated position</small></div>`;
 $('#pool-cards').innerHTML=poolWeights.map((p,i)=>{
 const eligible=v.valid&&v.term>=p.left,payout=eligible?(p.balanceUsd+v.feeUsd*p.bps/10000)*.9975*v.share:0,progress=(p.days-p.left)/p.days*100;
 return `<article class="card pool-card pool-tone-${i}"><div class="pool-top"><span>SAMPLE CYCLE</span><span class="pool-live">PREVIEW · ${c.name.toUpperCase()}</span></div><h3>${p.days}-Day ${p.bitcoin?'Bitcoin ':''}Pool</h3><div class="pool-value">${f(p.balanceUsd/poolPrice(p),8)} <small>${poolUnit(p)}</small></div><div class="pool-usd">≈ $${f(p.balanceUsd,2)} USD · sample balance</div><div class="pool-row"><span>Closes</span><strong>In ${p.left} days · sample</strong></div><div class="pool-row"><span>Your estimated share</span><strong>${eligible?f(v.share*100,4)+'%':v.valid?'Term ends before deadline':'Enter a valid burn'}</strong></div><div class="pool-row"><span>Estimated payout</span><strong>${f(payout/poolPrice(p),8)} ${poolUnit(p)}<small>≈ $${f(payout,2)} USD</small></strong></div><div class="progress-track" role="progressbar" aria-label="${p.days}-day sample cycle elapsed" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${progress.toFixed(1)}"><span style="width:${progress}%"></span></div><div class="pool-foot">${f(progress,1)}% of sample cycle elapsed · ${f(p.bps/100,2)}% of protocol fees</div></article>`;
 }).join('');
}
